### ISSUE TITLE
Does not work in my project???

### ISSUE THREAD

**Issue by strataga** [GeekyAnts/native-base-sticky-header#1]
"expo": "^20.0.0",
"native-base": "2.3.1",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
"redux": "^3.7.2",

I get no errors. I coped the code verbatim from the src/Application.js.

![screen shot 2017-09-14 at 11 12 08 pm](https://user-images.githubusercontent.com/10903600/30466256-3335c48a-99a2-11e7-8fb7-c19e36450bf5.png)

**Comment by SupriyaKalghatgi** [comment]
@appjitsu We will get back to you

**Comment by SupriyaKalghatgi** [comment]
@Jasbir23

**Comment by Jasbir23** [comment]
@appjitsu have you tried cloning the project and then running it?
Its difficult to identify the problem without information about your project
